$(function(){
	$("#tr-none-one").css({
		"display":"none",
	});
	$("#tr-none-two").css({
		"display":"none",
	});
	$("#tr-none-three").css({
		"display":"none",
	});
	$("#tr-none-four").css({
		"display":"none",
	});
	$("#tr-none-five").css({
		"display":"none",
	});
	$("#tr-none-six").css({
		"display":"none",
	});
	$("#tr-none-1").css({
		"display":"none",
	});
	$("#tr-none-2").css({
		"display":"none",
	});
	$("#tr-none-3").css({
		"display":"none",
	});
	
	
});