$(function(){
	$(".tr-none-one").css({
		"display":"none",
	});
	
	$("#tr-none-three").css({
		"display":"none",
	});
	$("#tr-none-four").css({
		"display":"none",
	});
	$("#tr-none-1").css({
		"display":"none",
	});
	$("#tr-none-2").css({
		"display":"none",
	});
	$("#tr-none-3").css({
		"display":"none",
	});
	$("#tr-none-4").css({
		"display":"none",
	});
	$("#tr-none-5").css({
		"display":"none",
	});
	$("#tr-none-6").css({
		"display":"none",
	});
	$("#tr-none-7").css({
		"display":"none",
	});
	$("#tr-none-8").css({
		"display":"none",
	});
	$("#tr-none-9").css({
		"display":"none",
	});
	$("#tr-none-10").css({
		"display":"none",
	});
	$("#tr-none-11").css({
		"display":"none",
	});
	$("#tr-none-12").css({
		"display":"none",
	});
	$("#tr-none-13").css({
		"display":"none",
	});
	$("#tr-none-14").css({
		"display":"none",
	});
	$("#tr-none-15").css({
		"display":"none",
	});
	$("#tr-none-16").css({
		"display":"none",
	});
	$("#tr-none-17").css({
		"display":"none",
	});
	$("#tr-none-18").css({
		"display":"none",
	});
	$("#tr-none-19").css({
		"display":"none",
	});
	$("#tr-none-20").css({
		"display":"none",
	});
	$("#tr-none-21").css({
		"display":"none",
	});
	$("#tr-none-22").css({
		"display":"none",
	});
	$("#tr-none-23").css({
		"display":"none",
	});
	$("#tr-none-24").css({
		"display":"none",
	});
	$(".sendMatch").click(function(){
		$(".tr-none-one").css({
			"display":"table-row"
		});
		$("#tr-emial input").prop("disabled",true);
		$("#tr-emial input").css({
			"margin":"0 auto",
			"outerline":"none",
			"border":"0px",
			"background":"#FBFDFD"
		});
	});
});